# Generated by Django 4.1 on 2022-09-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Compromisso',
        ),
    ]
